"""initial schema

Revision ID: ba9b19ba87d2
Revises:
Create Date: 2026-07-12 22:11:29.867766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba9b19ba87d2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column("cars", "color", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "cars",
        "engine_type",
        existing_type=postgresql.ENUM(
            "PETROL", "DIESEL", "HYBRID", "ELECTRIC", name="enginetype"
        ),
        nullable=False,
    )
    op.alter_column(
        "cars",
        "fuel_type",
        existing_type=postgresql.ENUM("UNLEADED", "PREMIUM", "DIESEL", name="fueltype"),
        nullable=False,
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(), nullable=True, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    op.alter_column(
        "cars",
        "fuel_type",
        existing_type=postgresql.ENUM("UNLEADED", "PREMIUM", "DIESEL", name="fueltype"),
        nullable=True,
    )
    op.alter_column(
        "cars",
        "engine_type",
        existing_type=postgresql.ENUM(
            "PETROL", "DIESEL", "HYBRID", "ELECTRIC", name="enginetype"
        ),
        nullable=True,
    )
    op.alter_column("cars", "color", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("cars", "updated_at")
    # ### end Alembic commands ###
