"""Small fixes in car model

Revision ID: c0de57832cb9
Revises: b4cfb4ac0447
Create Date: 2026-07-12 20:29:16.737371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0de57832cb9'
down_revision: Union[str, Sequence[str], None] = 'b4cfb4ac0447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cars', 'engine_type',
               existing_type=postgresql.ENUM('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', name='enginetype'),
               nullable=True)
    op.alter_column('cars', 'fuel_type',
               existing_type=postgresql.ENUM('UNLEADED', 'PREMIUM', 'DIESEL', name='fueltype'),
               nullable=True)
    op.drop_column('cars', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('cars', 'fuel_type',
               existing_type=postgresql.ENUM('UNLEADED', 'PREMIUM', 'DIESEL', name='fueltype'),
               nullable=False)
    op.alter_column('cars', 'engine_type',
               existing_type=postgresql.ENUM('PETROL', 'DIESEL', 'HYBRID', 'ELECTRIC', name='enginetype'),
               nullable=False)
    op.alter_column('cars', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
